spring:
  datasource:
    url: jdbc:h2:file:./data/cdr_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # Включает консоль H2
      path: /h2-console # URL для доступа к консоли
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Автоматическое создание/обновление таблиц
    show-sql: true # Показывать SQL-запросы в логах